### ISSUE TITLE
kots preflight checks do not match helm CLI preflight checks

### ISSUE THREAD

**Issue by dexhorthy** [slackernews/slackernews#27]
can we consolidate these? 

https://github.com/slackernews/slackernews/blob/main/chart/slackernews/templates/preflights.yaml

https://github.com/slackernews/slackernews/blob/main/kots/preflight.yaml

**Comment by crdant** [comment]
We should. No need for a distinct KOTS preflight, teaches bad habits

**Comment by dexhorthy** [comment]
looks like this happened at some point in the last few weeks
